# Словари для вызова комманд разными способами
start_dict = ['/start', 'start']
next_dict = ['/next', 'next', 'след', 'следующая', 'дальше']
help_dict = ['/help', 'help', 'помощь', 'памагити']
weather_dict = ['/weather', 'weather', 'погода', 'прогноз']
tt_dict = ['/tt', 'tt', '/timetable', 'timetable', 'расписание']
tod_dict = ['/tod', 'tod', 'сегодня', 'пары']
tom_dict = ['/tom', 'tom', 'завтра']
changelog_dict = ['/changelog', 'changelog', 'что нового', 'что нового?']
greet_dict = ['привет', 'дорова', 'дарова', 'здарова', 'йоу', 'шалома нахуй']
bus_dict = ['/bus', 'bus']
alt_dict = ['/alt', 'alt']
weekdays_dict_en = ['mon', 'tue', 'wed', 'thu', 'wed', 'sat', 'sun']
weekdays_dict_ru = ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье']
